experimental_monorepo_root = true

[monorepo]
config_roots = [
  ".github",
  "features",
  "src/database/bootstrap",
  "src/service",
  "src/ui",
]

[tools]
changie = "latest"

[tasks.lint]
description = "Lint all files in all projects"
depends = ["//...:lint"]

[tasks.test]
description = "Run all tests for all projects"
depends = ["//...:test"]
