experimental_monorepo_root = true

[monorepo]
config_roots = [
  ".github",
  "features",
  "infra",
  "src/database",
  "src/service",
  "src/ui",
]

[tools]
age = "latest"
changie = "latest"
fnox = "latest"

[tasks.init]
description = "Initialise environment for running"
depends = ["//...:init"]

[tasks.lint]
description = "Lint all files in all projects"
depends = ["//...:lint"]

[tasks.test]
description = "Run all tests for all projects"
depends = ["//...:test"]
