[tools]
terraform = "latest"
tflint = "latest"

[tasks.lint]
description = "Lint terraform configuration"
run = '''
  tflint
  terraform fmt -check
'''

[tasks.init]
description = "Initialise terraform"
usage = '''
arg "<environment>" {
  choices "dev" "prod"
  help "Target environment"
  default "dev"
  env "ENV"
}
'''
run = 'terraform init -backend-config="./vars/${usage_environment}/backend.hcl"'

[tasks.plan]
description = "Plan terraform deployment"
depends = ["init"]
usage = '''
arg "<environment>" {
  choices "dev" "prod"
  help "Target environment"
  default "dev"
  env "ENV"
}
flag "-o --output <file>" help="Output plan file"
'''
run = 'terraform plan -var-file="./vars/${usage_environment}/vars.tfvars" -var-file="./vars/common.tfvars" ${usage_output:+-out=}${usage_output}'

[tasks.apply]
description = "Apply terraform changes"
depends = ["init"]
usage = '''
arg "<environment>" {
  choices "dev" "prod"
  help "Target environment"
  default "dev"
  env "ENV"
}
flag "-i --input <file>" help="Optional input plan file"
'''
run = 'terraform apply -var-file="./vars/${usage_environment}/vars.tfvars" -var-file="./vars/common.tfvars" ${usage_input}'

