[tools]
node = "latest"
pnpm = { version = "latest", postinstall = "pnpm dlx playwright install --with-deps" }

[deps.pnpm]
auto = true

[tasks.lint]
description = "Run lint for the ui project"
run = "pnpm run lint"

[tasks.dev]
description = "Startup the ui development server"
run = "pnpm run dev"

[tasks.test-spec]
description = "Run the specification tests for the ui project"
run = "pnpm run test:spec"

[tasks.test]
description = "Run all tests for the ui project"
depends = ["test-*"]
