name: CI (GitHub workflows)

on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v6
      - name: 🚚 Install mise-en-place
        uses: jdx/mise-action@v4
        with:
          experimental: true
      - name: 🕵️ Run lint
        run: mise run //.github:lint

