name: Deploy infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: environment
        default: dev

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v6
      - name: 🔑 Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      - name: 🚚 Install mise-en-place
        uses: jdx/mise-action@v4
        with:
          experimental: true
      - name: 🎨 Plan changes
        run: mise run //infra:plan ${{ inputs.environment }} --output infra-plan.tfplan
      - name: 📥 Save plan
        id: artifact-upload-step
        uses: actions/upload-artifact@v7
        with:
          name: infra-plan
          path: ./infra-plan.tfplan
          retention-days: 5

  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment }}
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v6
      - name: 📤 Retrieve plan
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.plan.outputs.artifact-id }}
      - name: 🔑 Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      - name: 🚚 Install mise-en-place
        uses: jdx/mise-action@v4
        with:
          experimental: true
      - name: 🖼️ Apply changes
        run: mise run //infra:apply ${{ inputs.environment }} --input infra-plan.tfplan

