name: Deploy to AWS S3
 
on:
  push:
    branches:
      - database
 
permissions:
  id-token: write
  contents: read
 
jobs:
  plan:
    name: Terraform Plan Job
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-2
 
      - name: Verify AWS identity
        run: aws sts get-caller-identity
      
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Terraform Plan
        run: |
          cd infra
          terraform init -backend-config="./vars/dev/backend.hcl"
          terraform plan -backend-config="./vars/dev/backend.hcl" -var-file="./vars/dev/vars.tf"



 
